method: TOTAL3D
resume: False
finetune: True
weight: ['~/Total3DUnderstanding/out/layout_estimation/2021-02-04T17\:31\:56.279201/model_best.pth', '~/Total3DUnderstanding/out/object_detection/2021-02-05T00\:17\:28.569363/model_best.pth', '~/Total3DUnderstanding/out/mesh_reconstruction/2021-02-05T09\:13\:59.375043/model_best.pth']
seed: 123
device:
  use_gpu: True
  gpu_ids: '0'
  num_workers: 8
data:
  dataset: sunrgbd
  split: data/sunrgbd/splits
  tmn_subnetworks: 2
  face_samples: 1
  with_edge_classifier: True
model:
  layout_estimation:
    method: PoseNet
    loss: PoseLoss
  object_detection:
    method: Bdb3DNet
    loss: DetLoss
  mesh_reconstruction:
    method: DensTMNet
    loss: ReconLoss
optimizer:
  method: Adam
  lr: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-08
  weight_decay: 1e-04
scheduler:
  patience: 5
  factor: 0.5
  threshold: 0.01
train:
  epochs: 100
  phase: 'joint' # 'layout_estimation' or 'object_detection' or 'joint'.
  freeze: ['mesh_reconstruction']
  batch_size: 32
test:
  phase: 'joint'
  batch_size: 32 
demo:
  phase: 'joint'
log:
  vis_path: visualization
  save_results: True
  vis_step: 100
  print_step: 50
  path: out/total3d




